AllCops:
  TargetRubyVersion: 2.6
  UseCache: true
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - "bazel-*/**/*"
    - "ruby/tests/gemspec/expected/*"

Layout/LineLength:
  Enabled: true
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 20

Metrics/AbcSize:
  Enabled: true
  Max: 40
