workspace(name = "coinbase_rules_ruby_example")

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "coinbase_rules_ruby",
    path = "../..",
)

load(
    "@coinbase_rules_ruby//ruby:deps.bzl",
    "ruby_register_toolchains",
    "rules_ruby_dependencies",
)

rules_ruby_dependencies()

ruby_register_toolchains(version = "2.6.5")

load("@coinbase_rules_ruby//ruby:defs.bzl", "ruby_bundle")

ruby_bundle(
    name = "bundle",
    excludes = {
        "mini_portile": ["test/**/*"],
    },
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
    version = "2.0.2",
)
