workspace(name = "coinbase_rules_ruby_integration")

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "coinbase_rules_ruby",
    path = "../../..",
)

load(
    "@coinbase_rules_ruby//ruby:deps.bzl",
    "ruby_register_toolchains",
    "rules_ruby_dependencies",
)

rules_ruby_dependencies()

ruby_register_toolchains()

load("@coinbase_rules_ruby//ruby:defs.bzl", "rb_bundle")

rb_bundle(
    # Name this not bundle to validate we aren't 
    # hardcoding bundle
    name = "integration_test_bundle",
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
)
